#!python
"""Post the program to make compatible outputs."""

import argparse
import json
from pathlib import Path
import sys
from uranie_launcher.data import Data, data_to_ascii

def main(arguments):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output_dirname",
        help="Name of the directory where to store the results of the transient")
    parser.add_argument(
        "output_filename",
        help="Name of the directory where to store the results")
    args = parser.parse_args(arguments)

    result_names = ('pi', 'pi2')
    data = Data(name="Pi",
                description="evaluatede value of Pi",
                headers=[Data.Header(name=name, value_type=Data.Types.DOUBLE, value_unit="")
                            for name in result_names])
    results = json.loads((Path(args.output_dirname) / "result.json").read_text())

    data.add_values([result for result in results.values()])
    data_to_ascii(data, Path(args.output_filename))

    return 0

if __name__ == "__main__":

    sys.exit(main(sys.argv[1:]))
